name: CI

on: [ push, pull_request ]

jobs:
  native-compilation:
    runs-on: windows-latest
    name: Native Compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Check CMake version
        run: cmake --version

      - name: Generate CMake project
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build -G Ninja

      - name: Build 64bit RelWithDebInfo DLL
        run: cmake --build ./build --config RelWithDebInfo --target Yimura.Menu.Enhanced --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/Yimura.Menu.Enhanced.dll")) {throw 1}

      - name: Rename DLL to Yimura.Menu.Enhanced-dev-{GITHUB_SHA}.dll
        run: |
          del Yimura.Menu.Enhanced-dev-*.dll
          del Yimura.Menu.Enhanced-dev-*.pdb
          ren Yimura.Menu.Enhanced.dll Yimura.Menu.Enhanced-dev-${{github.sha}}.dll
          ren Yimura.Menu.Enhanced.pdb Yimura.Menu.Enhanced-dev-${{github.sha}}.pdb
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: RelWithDebInfo-Native-Clang
          path: |
            build/Yimura.Menu.Enhanced-dev-*.dll
            build/Yimura.Menu.Enhanced-dev-*.pdb

  cross-compilation:
    runs-on: ubuntu-latest
    name: Cross-compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Check Packages Versions
        run: |
          cmake --version
          ninja --version
          zig version

      - name: Generate CMake project
        run: cmake -DUSE_CROSSCOMPILER=Zig -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build -G Ninja

      - name: Build 64bit RelWithDebInfo DLL
        run: cmake --build ./build --config RelWithDebInfo --target Yimura.Menu.Enhanced --

      - name: Check if DLL got built
        run: if [ ! -f build/libYimura.Menu.Enhanced.dll ]; then exit 1; fi

      - name: Rename DLL to libYimura.Menu.Enhanced-dev-{GITHUB_SHA}.dll
        run: |
          mv libYimura.Menu.Enhanced.dll libYimura.Menu.Enhanced-dev-${{github.sha}}.dll
          mv libYimura.Menu.Enhanced.pdb libYimura.Menu.Enhanced-dev-${{github.sha}}.pdb
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: RelWithDebInfo-Cross
          path: |
            build/libYimura.Menu.Enhanced-dev-*.dll
            build/libYimura.Menu.Enhanced-dev-*.pdb
